CREATE TABLE IF NOT EXISTS users
(
    id     BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email  VARCHAR(254) NOT NULL,
    name   VARCHAR(250) NOT NULL,
	
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
	
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title  VARCHAR(50) NOT NULL,
    pinned BOOLEAN,
	
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title              VARCHAR(120)  NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    annotation         VARCHAR(2000) NOT NULL,
    event_date         TIMASTAMP without time zone,
    created_on         TIMASTAMP without time zone,
    published_on       TIMASTAMP without time zone,
    participant_limit  INTEGER,
    request_moderation BOOLEAN default true,
    paid               BOOLEAN,
	lat                FLOAT NOT NULL,
	lon                FLOAT NOT NULL,
    state              VARCHAR,
    category_id        BIGINT,
    initiator_id       BIGINT,
    location_id        BIGINT,
	
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_events_category_id FOREIGN KEY (category_id)
    REFERENCES categories (id),
    CONSTRAINT fk_events_initiator_id FOREIGN KEY (initiator_id)
    REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    event_id       BIGINT NOT NULL,
    compilation_id BIGINT NOT NULL,
	
    CONSTRAINT pk_events_compilations PRIMARY KEY (event_id, compilation_id),
    CONSTRAINT fk_events_compilations_compilation_id FOREIGN KEY (compilation_id)
    REFERENCES compilations (id),
    CONSTRAINT fk_events_compilations_event_id FOREIGN KEY (event_id)
    REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_id     BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    created      TIMASTAMP without time zone,
    status       VARCHAR,
	
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT fk_requests_event FOREIGN KEY (event_id)
    REFERENCES events (id),
    CONSTRAINT fk_requests_requester FOREIGN KEY (requester_id)
    REFERENCES users (id)
);